// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address": {
            "post": {
                "description": "обнавление адреса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Address",
                "operationId": "address",
                "parameters": [
                    {
                        "description": "Ввести название например улицы или Не важно",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateAddress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/area": {
            "post": {
                "description": "обнавление площади",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Area",
                "operationId": "area",
                "parameters": [
                    {
                        "description": "json area",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateArea"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/balcony": {
            "post": {
                "description": "обнавление ложия или балкон",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Balcony",
                "operationId": "balcony",
                "parameters": [
                    {
                        "description": "Типы балконо: Не важно или Лоджия или Балкон, All все с большой буквы",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateTypeBalcony"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/buildingYear": {
            "post": {
                "description": "обнавление года постройки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "BuildingYear",
                "operationId": "building-year",
                "parameters": [
                    {
                        "description": "building_year1 строго с 2010, building_year2 любое",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateBuildingYear"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/category": {
            "post": {
                "description": "обнавление категории дома",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Category",
                "operationId": "category",
                "parameters": [
                    {
                        "description": "Вводить 1 из 3: Только квартиры или Квартиры и апартаменты или Только апартаменты все с большой буквы!!",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/create": {
            "post": {
                "description": "Добавление всех фильтров и регистрация разом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "RegistrationUser",
                "operationId": "registration-user",
                "parameters": [
                    {
                        "description": "регистрация все фильтров пользователю",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createFilter"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/default": {
            "post": {
                "description": "обнавление дефолта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Default",
                "operationId": "default",
                "parameters": [
                    {
                        "description": "для дефолта",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateDefault"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/floors": {
            "post": {
                "description": "обнавление этажей",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Floors",
                "operationId": "floors",
                "parameters": [
                    {
                        "description": " или Только не первый или Только не последний или All",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateFloors"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/jk": {
            "post": {
                "description": "обнавление ЖК",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "JK",
                "operationId": "jk",
                "parameters": [
                    {
                        "description": "Ввести название жк или Не важно",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateJK"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/jk/add": {
            "post": {
                "description": "запись на повтор жк",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "AddReverseSweepJK",
                "operationId": "add-reverse-sweep-jk",
                "parameters": [
                    {
                        "description": "kek",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ReverseJK"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Всегда после /start",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "CheckUserRegistered",
                "operationId": "register-or-login",
                "parameters": [
                    {
                        "description": "регистрация по телеграмм юзер айди",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UserSignUpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "bool"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/metro": {
            "post": {
                "description": "обнавление метро",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Metro",
                "operationId": "metro",
                "parameters": [
                    {
                        "description": "Вводить или название метро или Не важно",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateMetro"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/metro/before": {
            "post": {
                "description": "обнавление до метро",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "MetroBefore",
                "operationId": "metro-before",
                "parameters": [
                    {
                        "description": "Вводить Только пешком с большой буквы или Не важно",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateMetroBefore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "ПИНГ",
                "summary": "Init",
                "operationId": "ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/price": {
            "post": {
                "description": "обнавление цены",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Price",
                "operationId": "price",
                "parameters": [
                    {
                        "description": "json price",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updatePrice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/repair": {
            "post": {
                "description": "обнавление ремонта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "RepairType",
                "operationId": "repair-type",
                "parameters": [
                    {
                        "description": "Типы ремонта строго такие: Чистовая, Черновая, Нет, Не важно",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateRepairType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/rooms": {
            "post": {
                "description": "обнавление комнат",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Rooms",
                "operationId": "rooms",
                "parameters": [
                    {
                        "description": "Название вводить строго такие: 1-комн (евродва), 2-комн (евротри), 3-комн, 4+комн, студия",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateRooms"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/search": {
            "post": {
                "description": "поиск",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск",
                "operationId": "search",
                "parameters": [
                    {
                        "description": "поиск по юзер айди фильтру с пагинацией",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.StartSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Advert"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/silence": {
            "post": {
                "description": "обнавление дефолта1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Silence",
                "operationId": "silence",
                "parameters": [
                    {
                        "description": "для дефолта1",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateSilence"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/subcategory": {
            "post": {
                "description": "обнавление субкатегории",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Subcategory",
                "operationId": "subcategory",
                "parameters": [
                    {
                        "description": "только Новостройка или Вторичка слова начинаются с большой буквы",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateSubcategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/subways": {
            "get": {
                "description": "все линий",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Subways",
                "operationId": "subways",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SubwayLines"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/user/create": {
            "post": {
                "description": "Добавление юзера если у него нет фильтров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "CreateUser",
                "operationId": "create-user",
                "parameters": [
                    {
                        "description": "Необходим user_id телеграма",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Filter"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/user/subway/lines": {
            "post": {
                "description": "автокомплит для линий метро",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetSubwayLines",
                "operationId": "get-subway-lines",
                "parameters": [
                    {
                        "description": "кверики",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.findLines"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SubwayLines"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Инфа о юзере",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUser",
                "operationId": "get-user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Необходим user_id телеграма",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Filter"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        },
        "/view/add": {
            "post": {
                "description": "Добавление объявлений в просмотренные",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "AdViewed",
                "operationId": "ad-viewed",
                "parameters": [
                    {
                        "description": "Необходим user_id телеграма и id циан объявления",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createView"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Advert": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "area": {
                    "type": "string"
                },
                "deadlineInfo": {
                    "type": "string"
                },
                "decoration": {
                    "type": "string"
                },
                "developer_name": {
                    "type": "string"
                },
                "floor_number": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "string"
                },
                "jk_fullUrl": {
                    "type": "string"
                },
                "jk_id": {
                    "type": "integer"
                },
                "jk_name": {
                    "type": "string"
                },
                "lat": {
                    "type": "string"
                },
                "lng": {
                    "type": "string"
                },
                "metro": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "rooms_count": {
                    "type": "string"
                },
                "subcategory": {
                    "type": "string"
                },
                "underground": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Metro"
                    }
                },
                "url": {
                    "type": "string"
                },
                "webSiteUrlUtm": {
                    "type": "string"
                }
            }
        },
        "domain.Filter": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "example Адрес ... либо пустое",
                    "type": "string"
                },
                "area1": {
                    "description": "example 55.9",
                    "type": "string"
                },
                "area2": {
                    "description": "example 76.0",
                    "type": "string"
                },
                "before_metro": {
                    "description": "example неважно, только пешком",
                    "type": "string"
                },
                "building_year1": {
                    "description": "example 2010",
                    "type": "integer"
                },
                "building_year2": {
                    "description": "example 2024",
                    "type": "integer"
                },
                "category": {
                    "description": "example только квартиры, квартиры и апартаменты, только апартаменты",
                    "type": "string"
                },
                "default": {
                    "type": "string"
                },
                "floors": {
                    "description": "example только не первый",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jk_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "jk_name": {
                    "description": "example ЖК ... либо пустое",
                    "type": "string"
                },
                "metro": {
                    "description": "example Речной вокзал",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price1": {
                    "description": "example 6459462",
                    "type": "integer"
                },
                "price2": {
                    "description": "example 7194195",
                    "type": "integer"
                },
                "repair_type": {
                    "description": "example euro",
                    "type": "string"
                },
                "rooms_count": {
                    "description": "example [1-комн (евродва),2-комн (евротри),3-комн,4+комн,студия]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "silence": {
                    "type": "string"
                },
                "subcategory": {
                    "description": "example Новостройка, Вторичка",
                    "type": "string"
                },
                "type_balcony": {
                    "description": "example неважно,балкон, лоджия",
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Metro": {
            "type": "object",
            "properties": {
                "cian_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "line_color": {
                    "type": "string"
                },
                "line_id": {
                    "type": "string"
                },
                "metro": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                },
                "transport_type": {
                    "type": "string"
                }
            }
        },
        "domain.ReverseJK": {
            "type": "object",
            "properties": {
                "jk_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.StartSearch": {
            "type": "object",
            "required": [
                "limit",
                "user_id"
            ],
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 1
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.SubwayLines": {
            "type": "object",
            "properties": {
                "line_id": {
                    "type": "string"
                },
                "line_name": {
                    "type": "string"
                }
            }
        },
        "domain.UserSignUpInput": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.createFilter": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "example ЖК ... либо пустое",
                    "type": "string",
                    "example": "Не важно"
                },
                "area1": {
                    "description": "example 55.9",
                    "type": "string",
                    "example": "80"
                },
                "area2": {
                    "description": "example 76.0",
                    "type": "string",
                    "example": "150"
                },
                "before_metro": {
                    "description": "example неважно, только пешком",
                    "type": "string",
                    "example": "Не важно"
                },
                "building_year1": {
                    "description": "example 2010",
                    "type": "integer",
                    "example": 2010
                },
                "building_year2": {
                    "description": "example 2024",
                    "type": "integer",
                    "example": 2024
                },
                "category": {
                    "description": "example только квартиры, квартиры и апартаменты, только апартаменты",
                    "type": "string",
                    "example": "Квартиры и апартаменты"
                },
                "floors": {
                    "description": "example только не первый",
                    "type": "string",
                    "example": "Только не первый"
                },
                "jk_name": {
                    "description": "example ЖК ... либо пустое",
                    "type": "string",
                    "example": "Не важно"
                },
                "metro": {
                    "description": "example Речной вокзал",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6",
                        "7",
                        "8",
                        "9",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "19",
                        "20",
                        "21",
                        "22",
                        "23",
                        "24",
                        "25",
                        "26",
                        "27",
                        "28",
                        "29",
                        "30",
                        "31",
                        "32",
                        "33",
                        "34",
                        "35"
                    ]
                },
                "price1": {
                    "description": "example 6459462",
                    "type": "integer",
                    "example": 10000000
                },
                "price2": {
                    "description": "example 7194195",
                    "type": "integer",
                    "example": 100000000
                },
                "repair_type": {
                    "description": "example euro",
                    "type": "string",
                    "example": "Не важно"
                },
                "rooms_count": {
                    "description": "example [1-комн (евродва),2-комн (евротри),3-комн,4+комн,студия]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1-комн (евродва)",
                        "2-комн (евротри)"
                    ]
                },
                "subcategory": {
                    "type": "string",
                    "example": "Новостройка"
                },
                "type_balcony": {
                    "description": "example неважно,балкон, лоджия",
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.createUser": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.createView": {
            "type": "object",
            "properties": {
                "cian_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.findLines": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "query": {
                    "type": "string"
                }
            }
        },
        "v1.result": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "v1.updateAddress": {
            "type": "object",
            "required": [
                "address",
                "user_id"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateArea": {
            "type": "object",
            "required": [
                "area1",
                "area2",
                "user_id"
            ],
            "properties": {
                "area1": {
                    "type": "string",
                    "example": "40"
                },
                "area2": {
                    "type": "string",
                    "example": "60"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateBuildingYear": {
            "type": "object",
            "required": [
                "building_year1",
                "building_year2",
                "user_id"
            ],
            "properties": {
                "building_year1": {
                    "type": "integer",
                    "example": 2010
                },
                "building_year2": {
                    "type": "integer",
                    "example": 2024
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateCategory": {
            "type": "object",
            "required": [
                "category",
                "user_id"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "example": "Квартиры и апартаменты"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateDefault": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "default": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateFloors": {
            "type": "object",
            "required": [
                "floors",
                "user_id"
            ],
            "properties": {
                "floors": {
                    "type": "string",
                    "example": "Только не последний"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateJK": {
            "type": "object",
            "required": [
                "jk_name",
                "user_id"
            ],
            "properties": {
                "jk_name": {
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateMetro": {
            "type": "object",
            "required": [
                "metro",
                "user_id"
            ],
            "properties": {
                "metro": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6",
                        "7",
                        "8",
                        "9",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "19",
                        "20",
                        "21",
                        "22",
                        "23",
                        "24",
                        "25",
                        "26",
                        "27",
                        "28",
                        "29",
                        "30",
                        "31",
                        "32",
                        "33",
                        "34",
                        "35"
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateMetroBefore": {
            "type": "object",
            "required": [
                "before_metro",
                "user_id"
            ],
            "properties": {
                "before_metro": {
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updatePrice": {
            "type": "object",
            "required": [
                "price1",
                "price2",
                "user_id"
            ],
            "properties": {
                "price1": {
                    "type": "integer",
                    "example": 7500000
                },
                "price2": {
                    "type": "integer",
                    "example": 9000000
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateRepairType": {
            "type": "object",
            "required": [
                "repair_type",
                "user_id"
            ],
            "properties": {
                "repair_type": {
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateRooms": {
            "type": "object",
            "required": [
                "rooms_count",
                "user_id"
            ],
            "properties": {
                "rooms_count": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1-комн (евродва)",
                        "2-комн (евротри)"
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateSilence": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "silence": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateSubcategory": {
            "type": "object",
            "required": [
                "subcategory",
                "user_id"
            ],
            "properties": {
                "subcategory": {
                    "type": "string",
                    "example": "Новостройка"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "v1.updateTypeBalcony": {
            "type": "object",
            "required": [
                "type_balcony",
                "user_id"
            ],
            "properties": {
                "type_balcony": {
                    "type": "string",
                    "example": "Не важно"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.1",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger .....",
	Description: "Api server for ....",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
